export const PEOPLE_FETCH_START = 'PEOPLE_FETCH_START';
export const PEOPLE_FETCH_SUCCESS = 'PEOPLE_FETCH_SUCCESS';
export const PEOPLE_FETCH_FAILED = 'PEOPLE_FETCH_FAILED';
export const PEOPLE_SORT = 'PEOPLE_SORT';